<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX542eg7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX542eg7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX542eg7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX542eg7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX542eg7\appProdProjectContainer(array(
    'container.build_hash' => 'X542eg7',
    'container.build_id' => 'eb22ed7a',
    'container.build_time' => 1542806759,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX542eg7');
