<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHbxiy3b\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHbxiy3b/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHbxiy3b.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHbxiy3b\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHbxiy3b\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hbxiy3b',
    'container.build_id' => '4164fafa',
    'container.build_time' => 1542807923,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHbxiy3b');
